### ISSUE TITLE
Gemstone port 

### ISSUE THREAD

**Issue by HeSe** [msgpack/msgpack-smalltalk#4]
Hi!

I ported this package to Gemstone.
To make Messagepack-Core loadable into Gemstone I had to change some code due to compiler restrictions.

MpConstants implements the following reserved methods.
nil
false
true

I renamed them to 
undefinedNil
boolFalse
boolTrue

This change also has to be introduced to all the senders of these methods.
All other needed changes can be handled via class extensions.

Would it be possible to add those changes to the MessagePack core?

Thanks
Sebastian

**Comment by mumez** [comment]
I think the changes are reasonable for the portability. I'll update Core package soon.

**Comment by mumez** [comment]
Updated. Please check the changes.
