### ISSUE TITLE
Pharo 4.0 String errors

### ISSUE THREAD

**Issue by HeSe** [msgpack/msgpack-smalltalk#5]
This script produces an error on Pharo 4.0 as well as on Gemstone.
The size of the to bytes converted String seems to be written wrong...

|dict|

dict := (Dictionary new at: '1234567890123456' put: data; yourself)
     messagePacked: [:settings | settings stringAsBytes: true ].

Object fromMessagePack: dict setting: [:se | se bytesAsString: true.]

**Comment by mumez** [comment]
Thank you for the report. I was able to reproduce the problem.

I think the problem is on Decoder. Because if you do not set the settings #bytesAsString to true, you can decode the dictionary anyway.

```
bytes := (Dictionary new at: '1234567890123456' put: 1; yourself) messagePacked: [:settings | settings stringAsBytes: true ].
"=> #[129 218 0 16 49 50 51 52 53 54 55 56 57 48 49 50 51 52 53 54 1]."
Object fromMessagePack: bytes.
"=> a Dictionary(#[49 50 51 52 53 54 55 56 57 48 49 50 51 52 53 54]->1 )"
Object fromMessagePack: bytes setting: [:settings | settings bytesAsString: true ].
"=> Error!"
```

**Comment by mumez** [comment]
Actually, MpDecodeTypeMapper>>bytesAsString was wrong. I carelessly overwrite "MpConstants str16" value of the mapping dictionary, so much longer string size decoder was activated.
