### ISSUE TITLE
Squeak 5.0 - 4 unit tests fail

### ISSUE THREAD

**Issue by KenDickey** [msgpack/msgpack-smalltalk#6]
Probably because of underlying representation change, several unit test fail under Squeak 5.0.

I am not a Squeak user and have not taken a close look at this.

FYI,
-KenD

**Comment by mumez** [comment]
Thank you for the report. I'll look into the details soon.

**Comment by mumez** [comment]
Squeak 5 introduces BoxedFloat64 and SmallFloat64 for representing floating point numbers.
We need to add encoders/decoders for those classes.
I think the situation is also same as in upcoming Pharo 5.0 spur version.

**Comment by mumez** [comment]
On development branch, I've added BoxedFloat64 and SmallFloat64 support. https://github.com/msgpack/msgpack-smalltalk/commit/9e76b80fd34fdac8e395904797c5199dab063136

**Comment by mumez** [comment]
Tests were all green on Squeak 5.0.
![test-results](https://cloud.githubusercontent.com/assets/705350/11913578/d5c82aee-a6ab-11e5-9fbb-0e2f5a8235c0.png)
